title: "Bundoora Scout Group"
description: ""
email: "gl.bundoora@scoutsvictoria.com.au"
encoding: utf-8

#Outputting
permalink: pretty
markdown: kramdown
highlighter: rouge
timezone: "Australia/Melbourne"

# Collections
collections:
  people:
    output: true

# Build settings
defaults:
  - 
    scope:
      path: ""
      type: people
    values:
      layout: text-page
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: text-page
  - 
    scope:
      path: "assets/images"
    values:
      image: true
  - 
    scope:
      path: ""
    values:
      layout: text-page

# Includes
include:
  - _pages

# Excludes
exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
 
 # Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

kramdown:
  hard_wrap: false
  input: GFM
#  smart_quotes: lsquo,rsquo,ldquo,rdquo

#sass:
#  style: compressed