title: "Bundoora Scout Group"
description: ""
email: "gl.bundoora@scoutsvictoria.com.au"
encoding: utf-8
url: "https://bundoorascouts.org"
author: "Bundoora Scout Group"

#Outputting
permalink: pretty
markdown: kramdown
highlighter: rouge
timezone: "Australia/Melbourne"
paginate: 5
paginate_path: "/the-campfire/page/:num/"

# Collections
collections:
  people:
    output: true

# Build settings
defaults:
  - 
    scope:
      path: ""
      type: people
    values:
      layout: text-page
      sitemap: false
      permalink: /about-us/our-leaders/:title
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /the-campfire/:year/:month/:title
  - 
    scope:
      path: "assets/images"
    values:
      image: true
  - 
    scope:
      path: ""
    values:
      layout: text-page

# Includes
include:
  - _pages

# Excludes
exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
 
 # Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
#  - jekyll-archives
#  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
#  - jekyll-archives
#  - jekyll-include-cache

kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  style: compressed

category_archive:
  type: liquid
  path: /the-campfire/category/
tag_archive:
  type: liquid
  path: /the-campfire/tag/

#jekyll-archives:
#  enabled:
#    - year
#    - categories
#    - tags
#  layout: default
#  layouts:
#    tag: tags
#    category: categories
#  permalinks:
#    year: '/the-campfire/:year/'
#    month: '/the-campfire/:year/:month/'
#    day: '/the-campfire/:year/:month/:day/'
#    tag: '/the-campfire/tag/:name/'
#    category: '/the-campfire/category/:name/'