title: Bundoora Scout Group
email: info@bundoorascouts.org
description: >-
  Bundoora Scout Group – The Modern Trailfinder. Empowering youth in Melbourne's
  north through adventure, leadership, and community service.
baseurl: ""
url: "https://bundoorascouts.org"
author: "Bundoora Scout Group"
repository: monkeyatcomputer/bundoorascouts.org
formspree_action: "https://formspree.io/f/mbjpklgn"
recapcha_site_key: "6LdSneEZAAAAALUuwv9omWFHmY2GipMHjMdzBD-D"
onboarding_url: "https://extranet.scoutsvictoria.com.au/scoutonline/public/onboarding_registration/trial-registration?sectionid="

# SEO
locale: en_AU
logo: /assets/images/logo.png
social:
  name: Bundoora Scout Group
  links:
    - https://facebook.com/bundoorascouts
facebook:
  publisher: https://facebook.com/bundoorascouts

# Build settings
theme: null

# Outputting
permalink: /:title
markdown: kramdown
highlighter: rouge
timezone: "Australia/Melbourne"

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-tailwind
  - jekyll-last-modified-at

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-tailwind
  - jekyll-last-modified-at

# Pagination
pagination:
  enabled: true
  per_page: 7
  offset: 0
  permalink: '/page/:num/'
  title: ':title Page :num'
  limit: 100
  sort_field: 'date'
  sort_reverse: true

kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# AutoPages
autopages:
  enabled: true
  categories:
    layouts:
      - blog.html
    permalink: /the-campfire/section/:cat
    slugify:
      mode: pretty
  collections:
    enabled: false
  tags:
    layouts:
      - blog.html
    permalink: /the-campfire/tag/:tag
    slugify:
      mode: pretty

# Collections
collections:
  people:
    output: false
  trips:
    output: true
    sort_field: date
    sort_reverse: true

# Feed
feed:
  disable_in_development: false
  excerpt_only: true
  tags: true

# Tailwind CSS
tailwind:
  input: assets/css/app.css
  minify: true

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - frontmatter.json
  - package.json
  - package-lock.json
  - README.md
  - SECURITY.md
  - .jekyll-cache/
  - artifacts/
  - docs/
  - node_modules/
  - scratch/
  - scripts/

# Build settings
defaults:
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /the-campfire/:year/:month/:title
  - 
    scope:
      path: "assets/images"
    values:
      image: true
  - 
    scope:
      path: ""
    values:
      layout: default