title: "Bundoora Scout Group"
description: ""
email: "gl.bundoora@scoutsvictoria.com.au"
encoding: utf-8
url: "https://bundoorascouts.org"
author: "Bundoora Scout Group"
repository: monkeyatcomputer/bundoorascouts.org
formspree_action: "https://formspree.io/f/mbjpklgn"

#Outputting
permalink: pretty
markdown: kramdown
highlighter: rouge
timezone: "Australia/Melbourne"
# Explicitly turn off the old code
#paginate: nil
#paginate_path: nil
#paginate: 5
#paginate_path: "/the-campfire/page/:num/"

# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  offset: 0
  permalink: '/page/:num/'
  title: ':title Page :num'
  limit: 100
  sort_field: 'date'
  sort_reverse: true

# AutoPages
autopages:
  enabled: true
  categories:
    layouts:
      - blog.html
    permalink: /the-campfire/section/:cat
    slugify:
      mode: pretty
  collections:
    enabled: false
  tags:
    layouts:
      - blog.html
    permalink: /the-campfire/tag/:tag
    slugify:
      mode: pretty

# Collections
collections:
  people:
    output: true
  awards:
    output: true

# Build settings
defaults:
  - 
    scope:
      path: ""
      type: people
    values:
      layout: text-page
      sitemap: false
      permalink: /about-us/our-leaders/:title
  - 
    scope:
      path: ""
      type: awards
    values:
      layout: text-page
      sitemap: false
      permalink: /about-us/awards/:title
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /the-campfire/:year/:month/:title
  - 
    scope:
      path: "assets/images"
    values:
      image: true
  - 
    scope:
      path: ""
    values:
      layout: text-page

# Includes
include:
  - _pages

# Excludes
exclude:
  - LICENSE
  - README.md
  - .gitignore
 
 # Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache

kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  style: compressed

#jekyll-archives:
#  enabled:
#    - year
#    - categories
#    - tags
#  layout: default
#  layouts:
#    tag: tags
#    category: categories
#  permalinks:
#    year: '/the-campfire/:year/'
#    month: '/the-campfire/:year/:month/'
#    day: '/the-campfire/:year/:month/:day/'
#    tag: '/the-campfire/tag/:name/'
#    category: '/the-campfire/category/:name/'